### ISSUE TITLE
Update readme.txt

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/datarc#13]
@codepixar - For this theme to be accepted on w.org, you need to update readme.txt file to mention ALL theme images/scripts/styles uses with corresponding licensing.

See this: https://github.com/ColorlibHQ/Mosh/blob/master/readme.txt

**Comment by codepixar** [comment]
@cristianraiber  - Update readme.text please check

**Comment by cristianraiber** [comment]
@codepixar - There's no way that background image used in the background is Colorlib licensed. If we upload this on w.org, he might get the theme suspended because images from Unsplash are prohibited. Especially when licensing declaration is missing. 

Please, look for the image on Pixabay.com (only site allowed). If it's not there, I'm afraid we will have to replace it with something very similar. 

Or, wait for @puikinsh to decide if this theme doesn't go on w.org.

**Comment by codepixar** [comment]
@cristianraiber - OK I will replace image from Pixabay.com.

**Comment by codepixar** [comment]
@cristianraiber  - Update readme file and change live demo image. Please check.

Thanks.

**Comment by cristianraiber** [comment]
@codepixar - it is my fault for not mentioning it before, but you should also update the screenshot.png file as well with the new image.

**Comment by codepixar** [comment]
@cristianraiber  - sorry it is my mistake.

**Comment by codepixar** [comment]
@cristianraiber - update screenshot.

**Comment by cristianraiber** [comment]
All good now.
