### ISSUE TITLE
404 page has no defaults

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/datarc#14]
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/7841556/47360596-91ab4200-d6d8-11e8-9bb5-38678151dc67.png">

**Comment by cristianraiber** [comment]
@codepixar - whatever's being displayed on the frontend, should be available to the user, after demo importer, in the backend as well. 

Please fix.

**Comment by codepixar** [comment]
@cristianraiber - Fixed this issue please check.
