### ISSUE TITLE
Footer Social should be a menu area

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/datarc#15]
Right now you've hardcoded that area to be social area, instead, you could make it be a menu area, like you did in the header with the Social Menu.

**Comment by codepixar** [comment]
@cristianraiber - I don't understand this issue. I have create social menu for header and footer social menu http://prntscr.com/l9wimg and create two toggle option to show / hide http://prntscr.com/l9ws0a  http://prntscr.com/l9ws8g

**Comment by cristianraiber** [comment]
@codepixar - Yes, but it is impossible to display anything else in that area in the footer. I can not assign another menu there, it's hardcoded. If I wanted to go ahead and display 2,3 links there, I can't do it right now.

Does this make more sense?

**Comment by codepixar** [comment]
@cristianraiber -Would you like? If i create  social icon option from customizer.

**Comment by cristianraiber** [comment]
@codepixar - Nope. Create a new menu in the footer. What would make me really happy would be another entry in here that says: "Footer Menu"

<img width="634" alt="image" src="https://user-images.githubusercontent.com/7841556/47488509-3353a000-d84d-11e8-8104-f343e5d0ab9c.png">

**Comment by codepixar** [comment]
@cristianraiber - Add footer menu http://prntscr.com/lac3rk

**Comment by cristianraiber** [comment]
@codepixar - you are close to what I want here. Please, move this:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/7841556/47562770-4a1af500-d928-11e8-8115-548fa891bf6f.png">


to replace this:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/7841556/47562784-599a3e00-d928-11e8-803f-8046021cdae2.png">

**Comment by cristianraiber** [comment]
I want to be able to replace the social footer menu with any other menu I want. I hope this makes sense now.

**Comment by codepixar** [comment]
@cristianraiber - I have removed footer social menu replace with footer menu. Please check.
Thanks.
