### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/datarc#16]
Navigating to "blog" from within the Customizer, the nav menu only features two links:

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/7841556/47360980-81e02d80-d6d9-11e8-93cd-cdb587c63cfe.png">

**Comment by codepixar** [comment]
@ristianraiber  - There has two type menu for header one is one page menu work only custom template and another is primary menu work in other page. http://prntscr.com/l9vjcs

**Comment by cristianraiber** [comment]
@codepixar - yep, I see this now. However, the back-end labelling for this is ... kinda off. Maybe you should look into address this as well with a future PR. 

Sorry I missed it, it wasn't easy to spot :)
