### ISSUE TITLE
Missing recommended action re. Demo Import

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/datarc#2]

**Comment by codepixar** [comment]
Already fixed please check.

**Comment by cristianraiber** [comment]
@codepixar - same discussion as in FasheWP. This is not fixed at all, why would you even say that? :) There's no code reference to this issue being fixed nor actual functionality on the frontend.

**Comment by codepixar** [comment]
@cristianraiber  - Add this action, It will show if not demo installed  http://prntscr.com/la7guu

**Comment by cristianraiber** [comment]
@codepixar - great job, now it looks properly :)
