### ISSUE TITLE
Theme Color (general -> theme options) doesn't do anything

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/datarc#3]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/7841556/46950545-a579f700-d08d-11e8-92d0-290213246b3a.png">

**Comment by codepixar** [comment]
Already fixed please check.

**Comment by cristianraiber** [comment]
@codepixar - changing the main theme color to red, affects most sections but still some are not working as advertised:

**Comment by cristianraiber** [comment]
<img width="1812" alt="image" src="https://user-images.githubusercontent.com/7841556/47360336-f0bc8700-d6d7-11e8-8a01-eb2b77b74a6c.png">

**Comment by cristianraiber** [comment]
<img width="1821" alt="image" src="https://user-images.githubusercontent.com/7841556/47360376-0762de00-d6d8-11e8-86e4-46608c093e89.png">

**Comment by cristianraiber** [comment]
<img width="1819" alt="image" src="https://user-images.githubusercontent.com/7841556/47360395-16e22700-d6d8-11e8-9bd2-a5241d596f80.png">

**Comment by cristianraiber** [comment]
<img width="1819" alt="image" src="https://user-images.githubusercontent.com/7841556/47360409-22cde900-d6d8-11e8-9a55-4fa24087db7e.png">

**Comment by cristianraiber** [comment]
@codepixar - I think in the last image, you should make the active state of the slider (the little dot that's currently with a darker grey) be with the accent color. So the accent is really there.

**Comment by codepixar** [comment]
@cristianraiber - It's work on theme color #00ff8c. Every elementor element has individual color  change option.

**Comment by cristianraiber** [comment]
@codepixar - your explanation makes absolutely no sense. Right now, the "Theme Color" color picker changes the accent color on a lot of element except a few. Please, make it change accent color on absolutely every element, because that is the purpose of this color picker. 

From my screenshots above you can see not all elements are changed. In Customizer, I am using red color, and on the frontend, some elements are red, some are green. 

Please fix.

**Comment by codepixar** [comment]
@cristianraiber - I'm doing something  and I think you will be happy :)

http://prntscr.com/lb20se 
http://prntscr.com/lb20wz 
http://prntscr.com/lb210z
http://prntscr.com/lb215z
http://prntscr.com/lb219q

Thanks.

**Comment by cristianraiber** [comment]
@codepixar - yep, this makes me mucho happy :) Thank you for implementing it.

**Comment by codepixar** [comment]
@codepixar  - You are welcome.

**Comment by cristianraiber** [comment]
@codepixar - Is this available in the latest PR? I didn't see it from the code comparison.

**Comment by codepixar** [comment]
@cristianraiber - It was not code problem. It was demo settings problem. I have update demo data in last PR.

**Comment by cristianraiber** [comment]
@codepixar - OK, cool. I will check!

**Comment by cristianraiber** [comment]
Now it works properly.
