### ISSUE TITLE
Design issue with header search icon

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/datarc#4]
<img width="1739" alt="image" src="https://user-images.githubusercontent.com/7841556/46950594-cfcbb480-d08d-11e8-9c20-e7c7a19364b1.png">

**Comment by cristianraiber** [comment]
When toggling "Social icons" to OFF, the search icon still has a big-ish border-right. It looks really bad.

**Comment by codepixar** [comment]
Already fixed please check.

**Comment by cristianraiber** [comment]
@codepixar - 
<img width="294" alt="image" src="https://user-images.githubusercontent.com/7841556/47360507-5c9eef80-d6d8-11e8-9add-f9bef7b072c0.png">

**Comment by cristianraiber** [comment]
You could rephrase these to say : "Toggle Header Search" && "Toggle Header Social"

**Comment by cristianraiber** [comment]
Sorry, going to leave this one open until you also rephrase the texts.

**Comment by codepixar** [comment]
@cristianraiber - Fixed this issue http://prntscr.com/l9wwuf

**Comment by cristianraiber** [comment]
@codepixar - Yes, but it is impossible to display anything else in that area in the footer. I can not assign another menu there, it's hardcoded. If I wanted to go ahead and display 2,3 links there, I can't do it right now.

Does this make more sense?

**Comment by cristianraiber** [comment]
@codepixar - good job!
