### ISSUE TITLE
Blog layout looks really bad

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/datarc#6]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/7841556/46950668-1b7e5e00-d08e-11e8-9154-7330bb904808.png">

**Comment by cristianraiber** [comment]
Please make sure this section looks good by creating somewhat of a styling for this page. Currently, the featured images are too small and by default, the blog doesn't have a sidebar which makes it look even worse. 

More so, if you're going to leave the blog without a sidebar, you should centre the content, not leave it "floating" to the left.

**Comment by codepixar** [comment]
Already fixed please check.
