### ISSUE TITLE
Footer panel improvements

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/datarc#8]
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/7841556/46950795-a6f7ef00-d08e-11e8-8a55-4a5d8f93279c.png">

**Comment by cristianraiber** [comment]
Textarea is empty, yet, I see a copyright message in the frontend.

**Comment by cristianraiber** [comment]
- Toggling "show footer widgets" to OFF should hide the corresponding color controls below the footer copyright textarea.

**Comment by codepixar** [comment]
Already fixed please check.

**Comment by cristianraiber** [comment]
@codepixar - please add another toggle here to completely hide the footer as well :) There are users who don't want/need a footer. 

There's also the issue of having extra space there even IF I don't have widgets: 

<img width="1818" alt="image" src="https://user-images.githubusercontent.com/7841556/47360897-48a7bd80-d6d9-11e8-9ae9-35ba9d81080f.png">

---

With widget area turned OFF, I should have minimal footer, just copyright message and social menu (the one on the right side)

**Comment by codepixar** [comment]
@cristianraiber  - I don't add toggle to hide footer completely, If hide footer completely it is not good to look other page http://prntscr.com/la6sxm. I think you wold like this :)  http://prntscr.com/la6oq7

**Comment by cristianraiber** [comment]
@codepixar - PLease add toggle to hide footer OFF completely but as post meta option, not globally. Some people will prefer ending their webpages in the purple call-to-action (see screenshot above this message) instead of the footer. 

The new CSS fixes for the footer also look good. Good job.

**Comment by cristianraiber** [comment]
Sorry, closed by mistake.

**Comment by codepixar** [comment]
@cristianraiber - Add meta option http://prntscr.com/labbb9

**Comment by cristianraiber** [comment]
Good job on this.
